name: absence_feature
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_bloc: ^9.0.0
  # networking
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  # barcode and QR code scanner for Flutter based on MLKit
  mobile_scanner: ^7.0.0
  # to implement value based equality
  equatable: ^2.0.7
  # to implement localization
  easy_localization: ^3.0.7+1
  # allows painting and displaying Scalable Vector Graphics
  flutter_svg: ^2.0.17
  # routing
  go_router: ^15.1.2
  qr_flutter: ^4.1.0
  syncfusion_flutter_charts: ^29.2.5
  easy_stepper: ^0.8.5+1
  flutter_form_builder: ^10.0.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lazy_load_indexed_stack: ^1.2.1
  retrofit_generator: ^9.1.9
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.3

  shared_core:
    git:
      url: https://github.com/Bassem320/flutter_shared_core.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.15

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
